### ISSUE TITLE
[OPTIONAL] Notifications of new message

### ISSUE THREAD

**Issue by valevassallo** [codeableorg/js-slack-clon#9]
- [ ]  When a message is received on the non-active channel and the page is visible

- [ ]  When a message is received on the active channel and the page is not visible

**Comment by byteconde** [comment]
Hey Vale, if it's an optional issue, you can use a different label like **feature-optional** 
![Screen Shot 2019-05-25 at 12 06 28 PM](https://user-images.githubusercontent.com/45726165/58372620-fc7a6100-7ee5-11e9-9a62-91039b6090d5.png)
Good job guys
